/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.Ventanas;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import proyecto.Main;
import proyecto.Ventanas.Paneles.*;

/**
 *
 * @author 8fdam02
 */
public class Ventana_gestion extends javax.swing.JFrame {

    /**
     * Creates new form EspectaculosParque
     */
    public Ventana_gestion() {
        initComponents();
        //visualizar_espectaculos(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Espectaculos = new javax.swing.JMenu();
        ver_pieza = new javax.swing.JMenuItem();
        anadir_pieza = new javax.swing.JMenuItem();
        borrar_pieza = new javax.swing.JMenuItem();
        menu_listadoPieza = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        ver_proveedor = new javax.swing.JMenuItem();
        anadir_proveedor = new javax.swing.JMenuItem();
        borrar_proveedor = new javax.swing.JMenuItem();
        menu_ListadoProveedor = new javax.swing.JMenuItem();
        m_empleado = new javax.swing.JMenu();
        ver_proyecto = new javax.swing.JMenuItem();
        anadir_proyecto = new javax.swing.JMenuItem();
        borrar_proyecto = new javax.swing.JMenuItem();
        menu_listadoProyecto = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        anadir_gestion = new javax.swing.JMenuItem();
        borrar_gestion = new javax.swing.JMenuItem();
        menu_listado_gestion = new javax.swing.JMenuItem();
        menu_consultas_gestion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1071, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menu_Espectaculos.setText("Piezas");

        ver_pieza.setText("Visualizar");
        ver_pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_piezaActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(ver_pieza);

        anadir_pieza.setText("Añadir");
        anadir_pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_piezaActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(anadir_pieza);

        borrar_pieza.setText("Borrar");
        borrar_pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_piezaActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(borrar_pieza);

        menu_listadoPieza.setText("Listado");
        menu_listadoPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listadoPiezaActionPerformed(evt);
            }
        });
        menu_Espectaculos.add(menu_listadoPieza);

        jMenuBar1.add(menu_Espectaculos);

        jMenu2.setText("Proveedores");

        ver_proveedor.setText("Visualizar");
        ver_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_proveedorActionPerformed(evt);
            }
        });
        jMenu2.add(ver_proveedor);

        anadir_proveedor.setText("Añadir");
        anadir_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_proveedorActionPerformed(evt);
            }
        });
        jMenu2.add(anadir_proveedor);

        borrar_proveedor.setText("Borrar");
        borrar_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_proveedorActionPerformed(evt);
            }
        });
        jMenu2.add(borrar_proveedor);

        menu_ListadoProveedor.setText("Listado");
        menu_ListadoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ListadoProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(menu_ListadoProveedor);

        jMenuBar1.add(jMenu2);

        m_empleado.setText("Proyectos");

        ver_proyecto.setText("Visualizar");
        ver_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_proyectoActionPerformed(evt);
            }
        });
        m_empleado.add(ver_proyecto);

        anadir_proyecto.setText("Añadir");
        anadir_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_proyectoActionPerformed(evt);
            }
        });
        m_empleado.add(anadir_proyecto);

        borrar_proyecto.setText("Borrar");
        borrar_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_proyectoActionPerformed(evt);
            }
        });
        m_empleado.add(borrar_proyecto);

        menu_listadoProyecto.setText("Listado");
        menu_listadoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listadoProyectoActionPerformed(evt);
            }
        });
        m_empleado.add(menu_listadoProyecto);

        jMenuBar1.add(m_empleado);

        jMenu1.setText("Gestión");

        anadir_gestion.setText("Añadir");
        anadir_gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadir_gestionActionPerformed(evt);
            }
        });
        jMenu1.add(anadir_gestion);

        borrar_gestion.setText("Borrar");
        borrar_gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar_gestionActionPerformed(evt);
            }
        });
        jMenu1.add(borrar_gestion);

        menu_listado_gestion.setText("Listado");
        menu_listado_gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listado_gestionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_listado_gestion);

        menu_consultas_gestion.setText("Consultas");
        menu_consultas_gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_consultas_gestionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_consultas_gestion);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrar_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_proveedorActionPerformed
        // TODO add your handling code here:
        Borrar_proveedor borrar_proveedor = new Borrar_proveedor();
        borrar_proveedor.setSize(1071,585);
        borrar_proveedor.setLocation(0,0);
        panel.removeAll();
        panel.add(borrar_proveedor,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_borrar_proveedorActionPerformed

    private void anadir_piezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_piezaActionPerformed
        // TODO add your handling code here:
        Anadir_pieza anadir_pieza = new Anadir_pieza();
        anadir_pieza.setSize(1071,585);
        anadir_pieza.setLocation(0,0);
        panel.removeAll();
        panel.add(anadir_pieza,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_anadir_piezaActionPerformed

    private void borrar_piezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_piezaActionPerformed
        // TODO add your handling code here:
        Borrar_pieza borrar_pieza = new Borrar_pieza();
        borrar_pieza.setSize(1071,585);
        borrar_pieza.setLocation(0,0);
        panel.removeAll();
        panel.add(borrar_pieza,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_borrar_piezaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main.Cancelar(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ver_piezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_piezaActionPerformed
        // TODO add your handling code here:
        Ver_pieza ver_pieza = new Ver_pieza();
        ver_pieza.setSize(1071,585);
        ver_pieza.setLocation(0,0);
        panel.removeAll();
        panel.add(ver_pieza,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_ver_piezaActionPerformed

    private void ver_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_proveedorActionPerformed
        // TODO add your handling code here:
        Ver_proveedor ver_proveedor = new Ver_proveedor();
        ver_proveedor.setSize(1071,585);
        ver_proveedor.setLocation(0,0);
        panel.removeAll();
        panel.add(ver_proveedor,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
        
    }//GEN-LAST:event_ver_proveedorActionPerformed

    private void anadir_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_proveedorActionPerformed
        // TODO add your handling code here:
        Anadir_proveedor anadir_proveedor = new Anadir_proveedor();
        anadir_proveedor.setSize(1071,585);
        anadir_proveedor.setLocation(0,0);
        panel.removeAll();
        panel.add(anadir_proveedor,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_anadir_proveedorActionPerformed

    private void ver_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_proyectoActionPerformed
        // TODO add your handling code here:
        Ver_proyecto ver_proyecto = new Ver_proyecto();
        ver_proyecto.setSize(1071,585);
        ver_proyecto.setLocation(0,0);
        panel.removeAll();
        panel.add(ver_proyecto,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_ver_proyectoActionPerformed

    private void anadir_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_proyectoActionPerformed
        // TODO add your handling code here:
        Anadir_proyecto anadir_proyecto = new Anadir_proyecto();
        anadir_proyecto.setSize(1071,585);
        anadir_proyecto.setLocation(0,0);
        panel.removeAll();
        panel.add(anadir_proyecto,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_anadir_proyectoActionPerformed

    private void borrar_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_proyectoActionPerformed
        // TODO add your handling code here:
        Borrar_proyecto borrar_proyecto = new Borrar_proyecto();
        borrar_proyecto.setSize(1071,585);
        borrar_proyecto.setLocation(0,0);
        panel.removeAll();
        panel.add(borrar_proyecto,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_borrar_proyectoActionPerformed

    private void anadir_gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadir_gestionActionPerformed
        // TODO add your handling code here:Listado_gestion listadoGestion = new Listado_gestion();
        Anadir_gestion anadir_gestion = new Anadir_gestion();
        anadir_gestion.setSize(1071,585);
        anadir_gestion.setLocation(0,0);
        panel.removeAll();
        panel.add(anadir_gestion,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_anadir_gestionActionPerformed

    private void borrar_gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar_gestionActionPerformed
        // TODO add your handling code here:
        Borrar_gestion borrar_gestion = new Borrar_gestion();
        borrar_gestion.setSize(1071,585);
        borrar_gestion.setLocation(0,0);
        panel.removeAll();
        panel.add(borrar_gestion,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_borrar_gestionActionPerformed

    private void menu_listadoPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listadoPiezaActionPerformed
        // TODO add your handling code here:
        Listado_pieza listadoPieza = new Listado_pieza();
        listadoPieza.setSize(1071,585);
        listadoPieza.setLocation(0,0);
        panel.removeAll();
        panel.add(listadoPieza,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_menu_listadoPiezaActionPerformed

    private void menu_ListadoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ListadoProveedorActionPerformed
        // TODO add your handling code here:
        Listado_proveedor listadoProveedor = new Listado_proveedor();
        listadoProveedor.setSize(1071,585);
        listadoProveedor.setLocation(0,0);
        panel.removeAll();
        panel.add(listadoProveedor,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_menu_ListadoProveedorActionPerformed

    private void menu_listadoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listadoProyectoActionPerformed
        // TODO add your handling code here:
        Listado_proyecto listadoProyecto = new Listado_proyecto();
        listadoProyecto.setSize(1071,585);
        listadoProyecto.setLocation(0,0);
        panel.removeAll();
        panel.add(listadoProyecto,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_menu_listadoProyectoActionPerformed

    private void menu_listado_gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listado_gestionActionPerformed
        // TODO add your handling code here:
        Listado_gestion listadoGestion = new Listado_gestion();
        listadoGestion.setSize(1071,585);
        listadoGestion.setLocation(0,0);
        panel.removeAll();
        panel.add(listadoGestion,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_menu_listado_gestionActionPerformed

    private void menu_consultas_gestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_consultas_gestionActionPerformed
        // TODO add your handling code here:
        Listado_consultas_gestion listadoConsultasGestion = new Listado_consultas_gestion();
        listadoConsultasGestion.setSize(1071,585);
        listadoConsultasGestion.setLocation(0,0);
        panel.removeAll();
        panel.add(listadoConsultasGestion,BorderLayout.CENTER);
        panel.revalidate();
        panel.repaint();
    }//GEN-LAST:event_menu_consultas_gestionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_gestion().setVisible(true);
            }
        });
    }
    public static void visualizar_espectaculos(JPanel desktop){
        Ver_proyecto ver_espectaculo = new Ver_proyecto();
        ver_espectaculo.setSize(1071,585);
        ver_espectaculo.setLocation(0,0);
        desktop.removeAll();
        desktop.add(ver_espectaculo,BorderLayout.CENTER);
        desktop.revalidate();
        desktop.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anadir_gestion;
    private javax.swing.JMenuItem anadir_pieza;
    private javax.swing.JMenuItem anadir_proveedor;
    private javax.swing.JMenuItem anadir_proyecto;
    private javax.swing.JMenuItem borrar_gestion;
    private javax.swing.JMenuItem borrar_pieza;
    private javax.swing.JMenuItem borrar_proveedor;
    private javax.swing.JMenuItem borrar_proyecto;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu m_empleado;
    private javax.swing.JMenu menu_Espectaculos;
    private javax.swing.JMenuItem menu_ListadoProveedor;
    private javax.swing.JMenuItem menu_consultas_gestion;
    private javax.swing.JMenuItem menu_listadoPieza;
    private javax.swing.JMenuItem menu_listadoProyecto;
    private javax.swing.JMenuItem menu_listado_gestion;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem ver_pieza;
    private javax.swing.JMenuItem ver_proveedor;
    private javax.swing.JMenuItem ver_proyecto;
    // End of variables declaration//GEN-END:variables
}
