/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;

import proyecto.Entidades.Proyectos;
import proyecto.Main;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import proyecto.Entidades.Gestion;

/**
 *
 * @author mario
 */
public class Anadir_gestion extends javax.swing.JPanel {
    Boolean error = false;

    /**
     * Creates new form Anadir_espectaculo
     */
    public Anadir_gestion() {
        initComponents();
        Main.getPiezasstoComboBox(cb_pieza);
        Main.getProveedortoComboBox(cb_proveedor);
        Main.getProyectotoComboBox(cb_proyecto);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_guardar = new javax.swing.JButton();
        cb_pieza = new javax.swing.JComboBox<>();
        cb_proveedor = new javax.swing.JComboBox<>();
        cb_proyecto = new javax.swing.JComboBox<>();
        n_cantidad = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1072, 717));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir gestion");

        jLabel2.setText("Pieza:");

        jLabel3.setText("proveedor:");

        jLabel5.setText("Proyecto:");

        b_guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_guardar.setText("Guardar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_pieza, 0, 236, Short.MAX_VALUE)
                            .addComponent(cb_proveedor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(n_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cb_proyecto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_pieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        String selectedPieza = cb_pieza.getSelectedItem().toString();
        String idPieza = selectedPieza.split("-")[0];
        
        String selectedProveedor = cb_proveedor.getSelectedItem().toString();
        String idProveedor = selectedProveedor.split("-")[0];
        
        String selectedProyecto = cb_proyecto.getSelectedItem().toString();
        String idProyecto = selectedProyecto.split("-")[0];
        
        Gestion existe = Main.getGestionByIds(idPieza, idProveedor, idProyecto);
        
        if (existe == null){
            if(Integer.parseInt(n_cantidad.getValue().toString()) >0){
                Gestion gestion = new Gestion();
                gestion.setIdPieza(idPieza);
                gestion.setIdProveedor(idProveedor);
                gestion.setIdProyecto(idProyecto);
                gestion.setCantidad(Integer.parseInt(n_cantidad.getValue().toString()) );
                Main.insertGestion(gestion);
            }
            else{
                JOptionPane.showMessageDialog(null, "Aumenta la cantidad seleccionada.");
            }

        }
        else{
            JOptionPane.showMessageDialog(null, "Esta gestion ya esta asociada");
        }
    }//GEN-LAST:event_b_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JComboBox<String> cb_pieza;
    private javax.swing.JComboBox<String> cb_proveedor;
    private javax.swing.JComboBox<String> cb_proyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner n_cantidad;
    // End of variables declaration//GEN-END:variables
}
