/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;

import proyecto.*;
import proyecto.Entidades.Pieza;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.sql.SQLException;

/**
 *
 * @author mario
 */
public class Anadir_pieza extends javax.swing.JPanel {
    Boolean error = false;

    /**
     * Creates new form Anadir_cliente
     */
    public Anadir_pieza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_nombre = new javax.swing.JTextField();
        n_precio = new javax.swing.JSpinner();
        b_anadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_descripcion = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir pieza");

        jLabel2.setText("ID:");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Precio:");

        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                try {
                    t_idFocusLost(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        t_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_nombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                try {
                    t_nombreFocusLost(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        n_precio.setMinimumSize(new java.awt.Dimension(84, 22));
        n_precio.setPreferredSize(new java.awt.Dimension(84, 22));
        n_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n_precioFocusGained(evt);
            }
        });

        b_anadir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_anadir.setText("Añadir ");
        b_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anadirActionPerformed(evt);
            }
        });

        t_descripcion.setColumns(20);
        t_descripcion.setRows(5);
        jScrollPane1.setViewportView(t_descripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(n_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addComponent(b_anadir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anadirActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(t_id.getText().isEmpty() ){
            cont++;
            t_id.setBorder(new LineBorder(Color.red,1));
        }
        if(t_nombre.getText().isEmpty() ){
            cont++;
            t_nombre.setBorder(new LineBorder(Color.red,1));
        }
        if(t_descripcion.getText().isEmpty()  ){
            cont++;
            t_descripcion.setBorder(new LineBorder(Color.red,1));;
        }
        if(n_precio.getValue().toString().equals('0') ){
            cont++;
            n_precio.setBorder(new LineBorder(Color.red,1));
        }

        if (cont == 0 && !error) {
            Pieza pieza = new Pieza();
            pieza.setId(t_id.getText());
            pieza.setNombre(t_nombre.getText());
            pieza.setDescripcion(t_descripcion.getText());
            pieza.setPrecio(Float.parseFloat((n_precio.getValue().toString())));

            Main.insertPieza(pieza);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
    }//GEN-LAST:event_b_anadirActionPerformed

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
        t_id.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_idFocusGained

    private void t_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_nombreFocusGained
        // TODO add your handling code here:
        t_nombre.setBorder(new LineBorder(Color.black,1));
        t_nombre.setForeground(Color.black);

        t_nombre.setText("");


    }//GEN-LAST:event_t_nombreFocusGained

    private void n_precioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_precioFocusGained
        // TODO add your handling code here:
        n_precio.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_n_precioFocusGained

    private void t_nombreFocusLost(java.awt.event.FocusEvent evt) throws SQLException {//GEN-FIRST:event_t_nombreFocusLost
        // TODO add your handling code here:
        String id = t_id.getText();
        Pieza p = Main.getIdPieza(id);
        if (p == null){
            error = false;
        }
        else {
            error = true;
        }
        if (error){
            t_id.setBorder(new LineBorder(Color.red,1));
            t_id.setText("ID ya utilizado");
            t_id.setForeground(Color.red);

        }

    }//GEN-LAST:event_t_nombreFocusLost
    private void t_idFocusLost(java.awt.event.FocusEvent evt) throws SQLException {//GEN-FIRST:event_t_nombreFocusLost
        // TODO add your handling code here:
        String id = t_id.getText();
        Pieza p = Main.getIdPieza(id);
        if (p == null){
            error = false;
        }
        else {
            error = true;
        }
        if (error){
            t_id.setBorder(new LineBorder(Color.red,1));
            t_id.setText("ID ya utilizado");
            t_id.setForeground(Color.red);

        }

    }//GEN-LAST:event_t_nombreFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anadir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner n_precio;
    private javax.swing.JTextArea t_descripcion;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombre;
    // End of variables declaration//GEN-END:variables
}
