/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;

import proyecto.Entidades.Proyectos;
import proyecto.Main;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;

/**
 *
 * @author mario
 */
public class Anadir_proyecto extends javax.swing.JPanel {
    Boolean error = false;

    /**
     * Creates new form Anadir_espectaculo
     */
    public Anadir_proyecto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_ciudad = new javax.swing.JTextField();
        b_guardar = new javax.swing.JButton();
        t_nombre = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1072, 717));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Añadir proyecto");

        jLabel2.setText("ID:");

        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_idFocusLost(evt);
            }
        });
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel5.setText("Ciudad:");

        t_ciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ciudadFocusGained(evt);
            }
        });

        b_guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_guardar.setText("Guardar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(629, 629, 629))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(430, 430, 430)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(t_id, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                .addComponent(t_nombre)))
                        .addGap(363, 363, 363))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if(t_id.getText().isEmpty() ){
            cont++;
            t_id.setBorder(new LineBorder(Color.red,1));
        }
        if(t_ciudad.getText().isEmpty() ){
            cont++;
            t_ciudad.setBorder(new LineBorder(Color.red,1));
        }
        if(t_nombre.getText().isEmpty() ){
            cont++;
            t_nombre.setBorder(new LineBorder(Color.red,1));
        }
        
        if (cont == 0){
            Proyectos proyecto = new Proyectos();
            proyecto.setId(t_id.getText());
            proyecto.setNombre(t_nombre.getText());
            proyecto.setCiudad(t_ciudad.getText());
            Main.insertProyecto(proyecto);
        }
        else{
            JOptionPane.showMessageDialog(null, "No dejes campos vacios");
        }
    }//GEN-LAST:event_b_guardarActionPerformed

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
        t_id.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_idFocusGained

    private void t_ciudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ciudadFocusGained
        // TODO add your handling code here:
        t_ciudad.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_ciudadFocusGained

    private void t_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusLost
        // TODO add your handling code here:
        String id = t_id.getText();
        Proyectos p = Main.getIdProyecto(id);
        if (p == null){
            error = false;
        }
        else {
            error = true;
        }
        if (error){
            t_id.setBorder(new LineBorder(Color.red,1));
            t_id.setText("ID ya utilizado");
            t_id.setForeground(Color.red);

        }
    }//GEN-LAST:event_t_idFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t_ciudad;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombre;
    // End of variables declaration//GEN-END:variables
}
