/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;

import proyecto.Entidades.Proyectos;
import proyecto.Main;

import javax.swing.border.LineBorder;
import java.awt.*;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author mario
 */
public class Ver_proyecto extends javax.swing.JPanel {

    /**
     * Creates new form Ver_espectaculo
     */
    public Ver_proyecto() {
        initComponents();
        Main.getProyectotoComboBox(cb_proyecto);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_guardar = new javax.swing.JButton();
        b_update_proyecto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        t_ciudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_proyecto = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ver proyecto");

        b_guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_guardar.setText("Editar");
        b_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_guardarActionPerformed(evt);
            }
        });

        b_update_proyecto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_update_proyecto.setText("Guardar");
        b_update_proyecto.setEnabled(false);
        b_update_proyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_update_proyectoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ciudad:");

        t_ciudad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_ciudadFocusGained(evt);
            }
        });

        jLabel2.setText("ID:");

        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_idFocusLost(evt);
            }
        });
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre:");

        jLabel10.setText("Seleccionar proyecto:");

        cb_proyecto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_proyectoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(287, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(419, 419, 419))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(b_update_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(263, 263, 263))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(95, 95, 95)
                                    .addComponent(t_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t_id)
                                            .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(cb_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)))
                        .addGap(307, 307, 307))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(t_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_update_proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_guardarActionPerformed
        // TODO add your handling code here:
        t_nombre.setEnabled(true);
        t_ciudad.setEnabled(true);
        
        b_update_proyecto.setEnabled(true);
    }//GEN-LAST:event_b_guardarActionPerformed

    private void b_update_proyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_update_proyectoActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        if (t_nombre.getText().isEmpty()) {
            cont++;
            t_nombre.setBorder(new LineBorder(Color.red, 1));
        }
        if (t_ciudad.getText().isEmpty()) {
            cont++;
            t_ciudad.setBorder(new LineBorder(Color.red, 1));
        }


        if (cont == 0) {
            String selectedValue = cb_proyecto.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];

            Main.updateProyecto(id, t_nombre.getText(), t_ciudad.getText());
            cb_proyecto.removeAllItems();
            Main.getProyectotoComboBox(cb_proyecto);

        }



    }//GEN-LAST:event_b_update_proyectoActionPerformed

    private void t_ciudadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_ciudadFocusGained
        // TODO add your handling code here:
        t_ciudad.setBorder(new LineBorder(Color.black,1));
    }//GEN-LAST:event_t_ciudadFocusGained

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
        t_id.setBorder(new LineBorder(Color.black,1));
    }//GEN-LAST:event_t_idFocusGained

    private void t_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idFocusLost

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void cb_proyectoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_proyectoItemStateChanged
        // TODO add your handling code here:
        //db.get_empleados();
        if(cb_proyecto.getItemCount() > 0) {
            String selectedValue = cb_proyecto.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];
            
            Proyectos p = Main.getIdProyecto(id);

            t_nombre.setText(p.getNombre());
            t_ciudad.setText(p.getCiudad());
            t_id.setText(p.getId());

            t_nombre.setEnabled(false);
            t_ciudad.setEnabled(false);
            t_id.setEnabled(false);

            b_update_proyecto.setEnabled(false);

        }

    }//GEN-LAST:event_cb_proyectoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_guardar;
    private javax.swing.JButton b_update_proyecto;
    private javax.swing.JComboBox<String> cb_proyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t_ciudad;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombre;
    // End of variables declaration//GEN-END:variables
}
