/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;


import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

import proyecto.Entidades.Pieza;
import proyecto.Main;

/**
 *
 * @author mario
 */
public class Ver_pieza extends javax.swing.JPanel {

    /**
     * Creates new form Ver_cliente
     */
    public Ver_pieza() {
        initComponents();
        Main.getPiezasstoComboBox(cb_pieza);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        t_nombre = new javax.swing.JTextField();
        n_precio = new javax.swing.JSpinner();
        b_edit_cliente = new javax.swing.JButton();
        b_update_cliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_pieza = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_descripcion = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(1071, 585));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Datos pieza");

        jLabel2.setText("ID:");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Precio:");

        t_id.setEnabled(false);
        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
        });
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        t_nombre.setEnabled(false);

        n_precio.setEnabled(false);
        n_precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                n_precioFocusGained(evt);
            }
        });

        b_edit_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_edit_cliente.setText("Editar datos");
        b_edit_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_edit_clienteActionPerformed(evt);
            }
        });

        b_update_cliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_update_cliente.setText("Guardar");
        b_update_cliente.setEnabled(false);
        b_update_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_update_clienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Selecciona la pieza:");

        cb_pieza.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    cb_piezaItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        cb_pieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_piezaActionPerformed(evt);
            }
        });

        t_descripcion.setColumns(20);
        t_descripcion.setRows(5);
        jScrollPane2.setViewportView(t_descripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(49, 49, 49)
                                        .addComponent(n_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel4)
                                        .addGap(24, 24, 24)
                                        .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(49, 49, 49)
                                .addComponent(cb_pieza, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(123, 123, 123)))
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(471, 471, 471))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(b_edit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(b_update_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cb_pieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(n_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_edit_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_update_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_edit_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_edit_clienteActionPerformed
        // TODO add your handling code here:
        t_nombre.setEnabled(true);      
        n_precio.setEnabled(true);
        t_descripcion.setEnabled(true);

        b_update_cliente.setEnabled(true);


    }//GEN-LAST:event_b_edit_clienteActionPerformed

    private void b_update_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_update_clienteActionPerformed
        // TODO add your handling code here:
        int cont = 0;
        
        if(t_nombre.getText().isEmpty() ){
            cont++;
            t_nombre.setBorder(new LineBorder(Color.red,1));
        }
        if(t_descripcion.getText().isEmpty() ){
            cont++;
            t_descripcion.setBorder(new LineBorder(Color.red,1));
        }
        if(n_precio.getValue().toString().equals('0') ){
            cont++;
            n_precio.setBorder(new LineBorder(Color.red,1));
        }
        
        if (cont == 0) {
            String selectedValue = cb_pieza.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];

            Main.updatePieza(id, t_nombre.getText(), t_descripcion.getText(),  Float.parseFloat(n_precio.getValue().toString() ) );
            cb_pieza.removeAllItems();
            Main.getPiezasstoComboBox(cb_pieza);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
    }//GEN-LAST:event_b_update_clienteActionPerformed

    private void cb_piezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_piezaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cb_piezaActionPerformed

    private void cb_piezaItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_cb_piezaItemStateChanged
        // TODO add your handling code here:
        if(cb_pieza.getItemCount() > 0){
            String selectedValue = cb_pieza.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];

            Pieza p = Main.getIdPieza(id);
            
            t_id.setText(p.getId());
            t_descripcion.setText(p.getDescripcion());
            t_nombre.setText(p.getNombre());
            n_precio.setValue(p.getPrecio());

            t_id.setEnabled(false);
            t_descripcion.setEnabled(false);
            n_precio.setEnabled(false);
            t_nombre.setEnabled(false);
            b_update_cliente.setEnabled(false);
        }

    }//GEN-LAST:event_cb_piezaItemStateChanged

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
        t_id.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_t_idFocusGained

    private void n_precioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_n_precioFocusGained
        // TODO add your handling code here:
        n_precio.setBorder(new LineBorder(Color.black,1));

    }//GEN-LAST:event_n_precioFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_edit_cliente;
    private javax.swing.JButton b_update_cliente;
    private javax.swing.JComboBox<String> cb_pieza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner n_precio;
    private javax.swing.JTextArea t_descripcion;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombre;
    // End of variables declaration//GEN-END:variables
}
