/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto.Ventanas.Paneles;

import java.awt.Color;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

import proyecto.Entidades.Pieza;
import proyecto.Entidades.Proveedor;
import proyecto.Main;


/**
 *
 * @author mario
 */
public class Ver_proveedor extends javax.swing.JPanel {

    Boolean error = false;
    /**
     * Creates new form Ver_empleado
     */
    public Ver_proveedor() {
        initComponents();
        Main.getProveedortoComboBox(cb_proveedor);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_update_emple = new javax.swing.JButton();
        b_editar_emple = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cb_proveedor = new javax.swing.JComboBox<>();
        t_nombre = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        t_cp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();

        setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ver proveedor");

        b_update_emple.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_update_emple.setText("Guardar");
        b_update_emple.setEnabled(false);
        b_update_emple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_update_empleActionPerformed(evt);
            }
        });

        b_editar_emple.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_editar_emple.setText("Editar");
        b_editar_emple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editar_empleActionPerformed(evt);
            }
        });

        jLabel10.setText("Seleccionar proveedor:");

        cb_proveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                try {
                    cb_proveedorItemStateChanged(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        t_nombre.setEnabled(false);

        t_apellido.setEnabled(false);

        t_cp.setEnabled(false);

        jLabel2.setText("ID:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Direccion:");

        t_id.setEnabled(false);
        t_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t_idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                t_idFocusLost(evt);
            }
        });
        t_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(65, 65, 65)
                                .addComponent(cb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGap(56, 56, 56))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_apellido)
                            .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_nombre)
                            .addComponent(t_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(251, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_editar_emple, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148)
                .addComponent(b_update_emple, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(t_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_update_emple, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_editar_emple, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_update_empleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_update_empleActionPerformed
        // TODO add your handling code here:
         int cont = 0;
        if(t_nombre.getText().isEmpty() ){
            cont++;
            t_nombre.setBorder(new LineBorder(Color.red,1));
        }
        if(t_apellido.getText().isEmpty() ){
            cont++;
            t_apellido.setBorder(new LineBorder(Color.red,1));
        }
        if(t_id.getText().isEmpty() ){
            cont++;
            t_id.setBorder(new LineBorder(Color.red,1));
        }
        if(t_cp.getText().isEmpty() ){
            cont++;
            t_cp.setBorder(new LineBorder(Color.red,1));
        }
        

        if (cont == 0 && !error) {
            String selectedValue = cb_proveedor.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];

            Main.updateProveedor(id, t_nombre.getText(), t_apellido.getText(), t_cp.getText());
            cb_proveedor.removeAllItems();
            Main.getProveedortoComboBox(cb_proveedor);
        }
        else{
            JOptionPane.showMessageDialog(null, "Revisa los datos");

        }
        
    }//GEN-LAST:event_b_update_empleActionPerformed

    private void b_editar_empleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editar_empleActionPerformed
        // TODO add your handling code here:
        t_nombre.setEnabled(true);
        t_apellido.setEnabled(true);
        t_cp.setEnabled(true);
        
        b_update_emple.setEnabled(true);


           
    }//GEN-LAST:event_b_editar_empleActionPerformed

    private void cb_proveedorItemStateChanged(java.awt.event.ItemEvent evt) throws SQLException {//GEN-FIRST:event_cb_proveedorItemStateChanged
        // TODO add your handling code here:
        //db.get_empleados();
        if(cb_proveedor.getItemCount() > 0) {
            String selectedValue = cb_proveedor.getSelectedItem().toString();
            String id = selectedValue.split("-")[0];

            Proveedor p = Main.getIdProveedor(id);


            t_nombre.setText(p.getNombre());
            t_apellido.setText(p.getApellido());
            t_cp.setText(p.getDireccion());
            t_id.setText(p.getId());
            

            t_nombre.setEnabled(false);
            t_apellido.setEnabled(false);
            t_cp.setEnabled(false);
            t_id.setEnabled(false);
          
            b_update_emple.setEnabled(false);

        }


        
    }//GEN-LAST:event_cb_proveedorItemStateChanged

    private void t_idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusGained
        // TODO add your handling code here:
        t_id.setBorder(new LineBorder(Color.black,1));
    }//GEN-LAST:event_t_idFocusGained

    private void t_idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t_idFocusLost
        // TODO add your handling code here:
        String id = t_id.getText();
        Proveedor p  = Main.getIdProveedor(id);
        if(p == null){
            error = true;
        }
        if(error){
            t_id.setBorder(new LineBorder(Color.red,1));
            t_id.setText("ID ya utilizado");
            t_id.setForeground(Color.red);
        }

    }//GEN-LAST:event_t_idFocusLost

    private void t_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_editar_emple;
    private javax.swing.JButton b_update_emple;
    private javax.swing.JComboBox<String> cb_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_cp;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nombre;
    // End of variables declaration//GEN-END:variables
}
